import { useAppStore } from '@/stores/appStore';
import { Button } from '@/components/ui/button';
import { motion } from 'framer-motion';
import { Sparkles, ArrowRight, Brain, Heart, Quote, Flame, Sunrise } from 'lucide-react';

const SPRING_TRANSITION = { type: 'spring', stiffness: 100, damping: 20 };

export function DashboardPage() {
  const { selectedChildId, children, setPage } = useAppStore();
  const selectedChild = children.find((c) => c.id === selectedChildId);
  
  if (!selectedChild) return <div className="p-8 text-center text-slate-500">Select a child to view dashboard</div>;

  const childAge = selectedChild.age;

  // Mocking the feed generated by the "Daily Content & Moments Feed Agent"
  // based on the meta-prompt architecture.
  const dailyFeed = [
    {
      id: 'encouragement',
      type: 'encouragement',
      icon: <Sunrise className="w-6 h-6 text-amber-500" />,
      title: 'Good Morning',
      content: `You are raising a child with high sensitivity (${selectedChild.temperament.sensitivity}%). Their big feelings are a feature, not a bug. They notice the beauty in the world that others miss.`,
      color: 'bg-amber-50 border-amber-100',
    },
    {
      id: 'developmental-cue',
      type: 'development',
      icon: <Brain className="w-6 h-6 text-sage" />,
      title: `Month ${childAge.months} Cognitive Leap`,
      content: `${selectedChild.name} is entering a phase of intense autonomy assertion. They aren't trying to make you late; they are practicing being an independent human.`,
      action: 'Read the science',
      color: 'bg-sage/10 border-sage/20',
    },
    {
      id: 'emotional-flashpoint',
      type: 'flashpoint',
      icon: <Flame className="w-6 h-6 text-rose-500" />,
      title: 'Likely Flashpoint Today: Transitions',
      content: `Because of their reaction intensity (${selectedChild.temperament.emotionalIntensity}%), abrupt transitions will likely cause meltdowns today.`,
      microScript: 'Instead of: "We are leaving right now!"\nTry: "In two minutes we are leaving. Do you want to hop to the door or march?"',
      color: 'bg-rose-50 border-rose-100',
    },
    {
      id: 'ritual',
      type: 'ritual',
      icon: <Heart className="w-6 h-6 text-accent" />,
      title: 'Suggested Ritual: The Evening Rose',
      content: `At dinner, ask ${selectedChild.name} for their "Rose" (best part of the day) and "Thorn" (hardest part). This builds emotional vocabulary and normalizes bad moments.`,
      action: 'Add to Family Hub',
      color: 'bg-accent/10 border-accent/20',
    },
    {
      id: 'reflection',
      type: 'reflection',
      icon: <Quote className="w-6 h-6 text-slate-700" />,
      title: 'Parent Reflection',
      content: 'When was the last time you felt truly overwhelmed, and what did you wish someone had said to you? Your child likely needs that exact same grace today.',
      color: 'bg-slate-100 border-slate-200',
    }
  ];

  return (
    <div className="max-w-2xl mx-auto pt-12 pb-32 px-4 sm:px-6">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={SPRING_TRANSITION}
        className="mb-12 text-center"
      >
        <p className="text-sm font-medium text-sage mb-4 tracking-widest uppercase">
          {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}
        </p>
        <h1 className="font-heading text-4xl md:text-5xl text-slate-850 leading-[1.1] mb-6">
          Your Daily Feed
        </h1>
        <p className="text-slate-500 text-lg max-w-md mx-auto">
          Personalized intelligence based on {selectedChild.name}'s specific neurological DNA.
        </p>
      </motion.div>

      <div className="space-y-8">
        {dailyFeed.map((item, index) => (
          <motion.div 
            key={item.id}
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ ...SPRING_TRANSITION, delay: index * 0.1 }}
            className={`p-8 rounded-[2.5rem] border ${item.color} relative overflow-hidden`}
          >
            <div className="flex items-start gap-4">
              <div className="mt-1 bg-white/50 backdrop-blur-sm p-3 rounded-full shadow-sm">
                {item.icon}
              </div>
              <div className="flex-1">
                <h3 className="font-heading font-semibold text-xl text-slate-850 mb-3">
                  {item.title}
                </h3>
                <p className="text-slate-700 leading-relaxed text-lg mb-4">
                  {item.content}
                </p>
                
                {item.microScript && (
                  <div className="mt-6 p-5 bg-white/60 rounded-2xl border border-white/40 shadow-sm">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Micro-Script</h4>
                    <p className="text-slate-800 font-medium whitespace-pre-line leading-relaxed">
                      {item.microScript}
                    </p>
                  </div>
                )}

                {item.action && (
                  <button className="mt-4 text-sm font-semibold text-slate-850 flex items-center hover:opacity-70 transition-opacity">
                    {item.action} <ArrowRight className="w-4 h-4 ml-1" />
                  </button>
                )}
              </div>
            </div>
          </motion.div>
        ))}

        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8 }}
          className="text-center pt-8"
        >
          <Sparkles className="w-6 h-6 text-slate-300 mx-auto mb-4" />
          <p className="text-slate-400 text-sm">You are caught up for today.</p>
        </motion.div>
      </div>
    </div>
  );
}
